# Generated by Django 6.0.1 on 2026-01-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ciudad', models.CharField(max_length=100)),
            ],
        ),
    ]
